### ISSUE TITLE
Bitangents Assimp and gltf

### ISSUE THREAD

**Issue by revolucas** [Planimeter/lgf#6]
I believe to get correct looking normals you need the mBitangent accessor from the aimesh and calculate the bitangentW in the shader as:

`vec3 bitangentW = normalize(vec3(model * vec4(bitangent.xyz, 0.0)));`

If you load up NormalTangentMirrorTest.gltf, you'll see the U and V mirror examples are messed up.

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentMirrorTest

**Comment by andrewmcwatters** [comment]
@revolucas Thanks for the heads up! I'm sure there's a few different permutations of available mesh data and default shaders that the framework doesn't yet support, and I didn't stumble upon this during my testing.

I'll check this out today.

**Comment by revolucas** [comment]
It's alright, mate, just making you aware of it. I don't personally need you to bust out of fix. If you need more detail, I can explain more thoroughly.

**Comment by andrewmcwatters** [comment]
Checking this out. I wonder why bitangent calculations are ending up incorrect, when the reference shader produces what should be the equivalent of them.

**Comment by andrewmcwatters** [comment]
Thanks for your help, @revolucas!
